### ISSUE TITLE
Remove scroll bar from right hand side and show it as part of the left most div container.

### ISSUE THREAD

**Issue by darmoment** [spectatorpublishing/NewShaft#532]
## Background
The [map](https://theshaft.info/explore) isn't scrollable but the left most div is. It's a little unintuitive for users.

<img width="1424" alt="Screen Shot 2023-01-22 at 10 57 50 AM" src="https://user-images.githubusercontent.com/65925033/213925800-827ed7fb-0f56-44d0-909c-bf598aab4f22.png">

**Comment by Etesam913** [comment]
https://www.figma.com/file/UqltfdLqRKqgRvDs8ClzcZ/theShaft-(2023)?node-id=0%3A1&t=M8G7IV4cT5UBB2Df-0
