### ISSUE TITLE
Create Housing Alert

### ISSUE THREAD

**Issue by zhuci** [spectatorpublishing/NewShaft#536]
Create a Housing Alert Component so we can add updates on specific dorms that have updates in housing process. 

You can create a new file in the components folder, then to make sure it works, try to create an example that overlays on the lottery page. We can also create a .json with all the messages, then if the lottery predictor is on that dorm, then that message will be displayed 

<img width="752" alt="image" src="https://user-images.githubusercontent.com/32231363/220791562-0340622f-5b25-4959-af31-92c3fce4e2f8.png">
<img width="289" alt="image" src="https://user-images.githubusercontent.com/32231363/220791576-11b6a800-b15b-4b67-bdbc-8eee2ecb2bbe.png">

https://www.figma.com/file/UqltfdLqRKqgRvDs8ClzcZ/theShaft-(2023)?node-id=0%3A1&t=M8G7IV4cT5UBB2Df-1

**Comment by Etesam913** [comment]
https://www.figma.com/file/UqltfdLqRKqgRvDs8ClzcZ/theShaft-(2023)?node-id=0%3A1&t=M8G7IV4cT5UBB2Df-0
